steps:
  # 1. Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/project-b56e5d64-2657-4923-937/introvert-backend-repo/node-api:$COMMIT_SHA', '-f', 'Dockerfile', '.']
  
  # 2. Push the image to your Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/project-b56e5d64-2657-4923-937/introvert-backend-repo/node-api:$COMMIT_SHA']

options:
  logging: CLOUD_LOGGING_ONLY